<?php
/**
 * Customer-facing cancel confirmation page.
 *
 * Rendered inside the active theme's get_header / get_footer chrome.
 * Receives the full booking variable bag plus:
 *   $just_cancelled  — true on the POST response, for a success flash
 *   $action_url      — where the confirm form POSTs
 *   $nonce_field     — pre-rendered wp_nonce_field HTML
 *
 * Status-aware branching:
 *   - cancelled        → success / already-cancelled message (no form)
 *   - completed/no_show→ "this booking can no longer be cancelled"
 *   - anything else    → summary + "Confirm cancel" button
 *
 * @package Timeslate
 */

declare( strict_types=1 );

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$status         = (string) ( $status ?? 'pending' );
$just_cancelled = ! empty( $just_cancelled );
$terminal       = in_array( $status, array( 'cancelled', 'completed', 'no_show' ), true );

?>
<?php if ( $just_cancelled ) : ?>
	<p class="timeslate-cancel-page__lead">
		<?php esc_html_e( 'Thanks for letting us know. Your booking has been cancelled and a confirmation has been emailed to you.', 'timeslate' ); ?>
	</p>
<?php elseif ( 'cancelled' === $status ) : ?>
	<p class="timeslate-cancel-page__lead">
		<?php esc_html_e( "This booking has already been cancelled. There's nothing more to do.", 'timeslate' ); ?>
	</p>
<?php elseif ( $terminal ) : ?>
	<p class="timeslate-cancel-page__lead">
		<?php esc_html_e( 'This booking can no longer be cancelled. If you need help, please contact us directly.', 'timeslate' ); ?>
	</p>
<?php else : ?>
	<p class="timeslate-cancel-page__lead">
		<?php esc_html_e( 'You are about to cancel the following booking:', 'timeslate' ); ?>
	</p>
<?php endif; ?>

<dl class="timeslate-cancel-page__summary">
	<div class="timeslate-cancel-page__row">
		<dt><?php esc_html_e( 'Name', 'timeslate' ); ?></dt>
		<dd><?php echo esc_html( (string) ( $name ?? '' ) ); ?></dd>
	</div>
	<div class="timeslate-cancel-page__row">
		<dt><?php esc_html_e( 'Date', 'timeslate' ); ?></dt>
		<dd><?php echo esc_html( (string) ( $date_long ?? '' ) ); ?></dd>
	</div>
	<div class="timeslate-cancel-page__row">
		<dt><?php esc_html_e( 'Time', 'timeslate' ); ?></dt>
		<dd><?php echo esc_html( (string) ( $time_pretty ?? '' ) ); ?></dd>
	</div>
	<div class="timeslate-cancel-page__row">
		<dt><?php esc_html_e( 'People', 'timeslate' ); ?></dt>
		<dd>
			<?php
			$people_num = (int) ( $people ?? 0 );
			echo esc_html(
				sprintf(
					/* translators: %d: number of people. */
					_n( '%d person', '%d people', $people_num, 'timeslate' ),
					$people_num
				)
			);
			?>
		</dd>
	</div>
	<div class="timeslate-cancel-page__row">
		<dt><?php esc_html_e( 'Status', 'timeslate' ); ?></dt>
		<dd><?php echo esc_html( (string) ( $status_label ?? $status ) ); ?></dd>
	</div>
</dl>

<?php if ( ! $just_cancelled && ! $terminal ) : ?>
	<form method="post" action="<?php echo esc_url( (string) ( $action_url ?? '' ) ); ?>" class="timeslate-cancel-page__form">
		<?php
		// $nonce_field is generated by wp_nonce_field() and is safe HTML.
		echo $nonce_field ?? ''; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		?>
		<button type="submit" class="timeslate-cancel-page__btn">
			<?php esc_html_e( 'Confirm cancellation', 'timeslate' ); ?>
		</button>
		<a href="<?php echo esc_url( (string) ( $site_url ?? home_url( '/' ) ) ); ?>" class="timeslate-cancel-page__back">
			<?php esc_html_e( 'Never mind, keep my booking', 'timeslate' ); ?>
		</a>
	</form>
<?php else : ?>
	<p class="timeslate-cancel-page__back-wrap">
		<a href="<?php echo esc_url( (string) ( $site_url ?? home_url( '/' ) ) ); ?>" class="timeslate-cancel-page__back">
			<?php esc_html_e( 'Back to the site', 'timeslate' ); ?>
		</a>
	</p>
<?php endif; ?>
