<?php
/**
 * Shared HTML shell for every outgoing booking email.
 *
 * Receives:
 *   $body       — rendered inner template as HTML string
 *   $type       — template slug (e.g. customer-confirmed)
 *   $site_name  — blog name
 *   $site_url   — home URL
 *   (other booking vars are available via extract, but this template
 *    deliberately only styles the chrome; the inner template prints
 *    the booking-specific content.)
 *
 * Kept table-based because that's what a broad swath of email clients
 * (Outlook, older Gmail / Yahoo) still render reliably. Inline styles,
 * not classes, for the same reason.
 *
 * @package Timeslate
 */

declare( strict_types=1 );

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$timeslate_site_name = (string) ( $site_name ?? get_option( 'blogname' ) );
$timeslate_site_url  = (string) ( $site_url ?? home_url( '/' ) );
$timeslate_body      = (string) ( $body ?? '' );

?><!DOCTYPE html>
<html lang="<?php echo esc_attr( get_bloginfo( 'language' ) ); ?>">
<head>
<meta charset="<?php echo esc_attr( get_bloginfo( 'charset' ) ); ?>">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title><?php echo esc_html( $timeslate_site_name ); ?></title>
</head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1e1e1e;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f5f5f5;padding:24px 0;">
	<tr>
		<td align="center">
			<table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.06);">
				<tr>
					<td style="padding:28px 32px 8px 32px;border-bottom:1px solid #ececec;">
						<a href="<?php echo esc_url( $timeslate_site_url ); ?>" style="text-decoration:none;color:#1e1e1e;font-weight:600;font-size:18px;letter-spacing:-0.01em;">
							<?php echo esc_html( $timeslate_site_name ); ?>
						</a>
					</td>
				</tr>
				<tr>
					<td style="padding:24px 32px 32px 32px;font-size:15px;line-height:1.55;color:#1e1e1e;">
						<?php
						// Inner template is generated by our own code with
						// escape-on-output throughout; trusted.
						echo $timeslate_body; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
						?>
					</td>
				</tr>
				<tr>
					<td style="padding:16px 32px 24px 32px;border-top:1px solid #ececec;font-size:12px;color:#8a8f94;text-align:center;">
						<?php
						printf(
							/* translators: %s: site name. */
							esc_html__( 'Sent by %s', 'timeslate' ),
							'<a href="' . esc_url( $timeslate_site_url ) . '" style="color:#8a8f94;text-decoration:none;">' . esc_html( $timeslate_site_name ) . '</a>'
						);
						?>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</body>
</html>
